spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhang

  session:
    store-type: none

portlet:
  security:
    browser:
      loginType: JSON
#      loginPage: /demo-signIn.html
    code:
      image:
        length: 3
        width: 100
        url: /user,/user/*
    social:
      qq:
        app-id:
        app-secret:
        providerId: callBack.do
      filterProcessesUrl: /qqLogin