spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhang

  session:
    store-type: none
server:
  port: 80
portlet:
  security:
    browser:
      loginType: JSON
#      loginPage: /demo-signIn.html
      signUpUrl: /demo-signUp.html
    code:
      image:
        length: 3
        width: 100
        url: /user,/user/*
    social:
      qq:
        app-id:
        app-secret:
        providerId: callBack.do
      filterProcessesUrl: /qqLogin
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4